[project]
name = "pydantic-srlinux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12"
dependencies = ["pydantify==0.6.1", "pyyaml>=6.0.2", "rich>=13.9.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["models"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
pydantify = { git = "https://github.com/dpeachey/pydantify", rev = "fix-nokia-models" }
